tasks:
  - init: > 
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/Minconda3.sh &&
      bash /tmp/Minconda3.sh -b -p /workspace/miniconda3 &&
      echo "export PATH=/workspace/miniconda3/bin:$PATH" >> ~/.bashrc &&
      source ~/.bashrc &&
      conda env create -n classifier_env -f envs_cpu.yaml

    command: >
      cd /workspace/classifier &&
      /workspace/miniconda3/envs/classifier_env/bin/python app.py


ports:
  - port: 8000
    onOpen: open-preview
